// All audit log action names — never use raw strings for action names.
export const AUDIT_ACTIONS = {
  // Crossing events
  CROSSING_EVENT_PROCESSED: 'CROSSING_EVENT_PROCESSED',

  // Sessions
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  PRESENCE_OVERRIDE: 'PRESENCE_OVERRIDE',

  // Export
  EMERGENCY_EXPORT: 'EMERGENCY_EXPORT',
  AUDIT_LOG_EXPORT: 'AUDIT_LOG_EXPORT',

  // Tags
  TAG_ASSIGNED: 'TAG_ASSIGNED',
  TAG_REVOKED: 'TAG_REVOKED',
  TAG_IMPORTED: 'TAG_IMPORTED',

  // Sync
  BLACKBAUD_SYNC_TRIGGERED: 'BLACKBAUD_SYNC_TRIGGERED',

  // Retention
  RETENTION_PURGE: 'RETENTION_PURGE',

  // Config
  RETENTION_CONFIG_UPDATED: 'RETENTION_CONFIG_UPDATED',

  // API access (generic)
  API_ACCESS: 'API_ACCESS',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
